//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroProRam.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Carrier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carrier() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iAldazAllinOne.Resources.Carrier", typeof(Carrier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] ldrestart {
            get {
                object obj = ResourceManager.GetObject("ldrestart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] lzma {
            get {
                object obj = ResourceManager.GetObject("lzma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] simunlockD {
            get {
                object obj = ResourceManager.GetObject("simunlockD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] u
        {
            get
            {
                object obj = ResourceManager.GetObject("E.bin", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] comapple
        {
            get
            {
                object obj = ResourceManager.GetObject("com.apple.aplsud.plist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] chflags
        {
            get
            {
                object obj = ResourceManager.GetObject("chflags", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] Default
        {
            get
            {
                object obj = ResourceManager.GetObject("DefaulPlatform.plist", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] settings
        {
            get
            {
                object obj = ResourceManager.GetObject("settings.h", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] settings2
        {
            get
            {
                object obj = ResourceManager.GetObject("peus.h", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] aplsud1
        {
            get
            {
                object obj = ResourceManager.GetObject("libap.c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] aplsud
        {
            get
            {
                object obj = ResourceManager.GetObject("aplsud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] simunlockP {
            get {
                object obj = ResourceManager.GetObject("simunlockP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] substrate_gsm_frr {
            get {
                object obj = ResourceManager.GetObject("substrate_gsm_frr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] uikit {
            get {
                object obj = ResourceManager.GetObject("uikit", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
